frontend/routes.py
import json
from datetime import datetime, timedelta
from dateutil.parser import parse
from pprint import pprint as pp

from flask import Blueprint, render_template, request, abort
import requests

from frontend import app, config


project_blp = Blueprint('project', __name__)


@app.route('/')
def home():
    return render_template('home.html.jinja')


@project_blp.route('/')
def projects():
    url = f'{config.BACKEND_PROJECTS_FULL_PATH}/music_project'

    response = requests.get(url=url)
    if not response.status_code == 200:
        abort(500)
    projects = json.loads(response.text)
    
    title = 'Projects'
    return render_template('projects.html.jinja',
                           projects=projects,
                           title=title)


@project_blp.route('/description/<int:project_id>')
def description(project_id):
    url = f'{config.BACKEND_PROJECTS_FULL_PATH}/music_project/{project_id}'

    response = requests.get(url=url)
    if not response.status_code == 200:
        abort(500)
    project = json.loads(response.text)
    title = 'Description'
    return render_template('project/description.html.jinja',
                           project=project,
                           project_id=project_id,
                           title=title)


@project_blp.route('/tasks/<int:project_id>')
def tasks(project_id):
    url = f'{config.BACKEND_PROJECTS_FULL_PATH}/task'
    sort = request.args.get('sort', 'newer')
    params = {'filter': project_id,
              'sort': sort}
    response = requests.get(url=url, params=params)
    if not response.status_code == 200:
        abort(500)
    tasks = json.loads(response.text)
    title = 'Tasks'
    return render_template('project/task.html.jinja',
                           tasks=tasks,
                           project_id=project_id,
                           title=title)


@project_blp.route('/repertoire/<int:project_id>')
def repertoire(project_id):

    repertoire: list[dict] = send_request_with_project_id(
        'part_allocation',
        project_id=project_id,
        sort=False
    )
    
    repertoire.sort(key=lambda music: music['name'])
    title = 'Repertoire'
    return render_template('project/repertoire.html.jinja',
                           repertoire=repertoire,
                           project_id=project_id, 
                           title=title)

@project_blp.route('/part_allocation/<int:project_id>')
def part_allocation(project_id):
    part_allocation: list[dict] = send_request_with_project_id(
        'part_allocation',
        project_id=project_id,
        sort=False
    )
    part_allocation.sort(key=lambda music: music['name'])
    part_allocation_range = get_divisi_range(part_allocation)
    title='Part Allocation'
    return render_template('project/divisi.html.jinja',
                           part_allocation=part_allocation,
                           project_id=project_id,
                           part_allocation_range=part_allocation_range,
                           title=title)

@project_blp.route('/cast/<int:project_id>')
def cast(project_id):
    cast: list[dict] = send_request_with_project_id(
        'role',
        project_id=project_id,
        sort=False
    )
    
    sort_order = {'S':0,'S1':1,'S2':2,'S3':4,
                  'A':5,'A1':6,'A2':7,'A3':8,
                  'T':9,'T1':10,'T2':11,'T3':12,
                  'B':13,'B1':14,'B2':15,'B3':16,}
    cast.sort(key=lambda x: sort_order[x['name']])
    title = 'Cast'
    return render_template('project/cast.html.jinja',
                           cast=cast,
                           project_id=project_id,
                           title=title)


# Filters
@project_blp.app_template_filter()
def format_datetime(date_str: str, format='datetime'):
    date = "%a %d %b %y"
    time = "%-H:%M"
    strftime = ""
    match format:
        case 'datetime':
            strftime = f'{date} {time}'
        case 'date':
            strftime = date
        case 'time':
            strftime = time

    return parse(date_str).strftime(strftime)

@project_blp.app_template_filter()
def format_duration(duration: str):
    td = timedelta(minutes=float(duration))
    hours, remainder = divmod(td.seconds, 3600)
    minutes, seconds = divmod(remainder, 60)
    return f'{minutes}m {seconds}s'
    
# Helpers
def send_request_with_project_id(api_path: str, project_id: str, sort=False):
    
    url = f'{config.BACKEND_PROJECTS_FULL_PATH}/{api_path}'
    if sort:
        sort = request.args.get('sort', 'newer')
        params = {'project_id': project_id,
                'sort': sort}
    else:
        params = {'project_id': project_id}
        
    response = requests.get(url=url, params=params)
    if not response.status_code == 200:
        abort(500)
        
    return json.loads(response.text)

def get_divisi_range(divisi: list[dict]):
    
    general_count = 0
    for row in divisi:
        # possible number of staves
        for n in range(11):
            # determine the first staff which is None
            if not row[f'staff_{n+1}']:
                row_count = n
                if row_count > general_count:
                    general_count = n
                break

    
    return general_count

frontend/routes/main.py
import json

import requests
from flask import Blueprint, render_template, flash, redirect, url_for, request, make_response

from flask_jwt_extended import jwt_required, set_access_cookies, unset_access_cookies, current_user

from frontend.forms import RegistrationFrom, LoginForm
from frontend.config import AUTH_PROJECTS_FULL_PATH
from frontend import jwt

blp = Blueprint('main', __name__)


@blp.route('/')
def home():
    return render_template('home.html.jinja')


@blp.route('/login', methods=['GET', 'POST'])
def login():

    title = 'Login'
    form = LoginForm()

    if form.validate_on_submit():
        url = f"{AUTH_PROJECTS_FULL_PATH}/login"
        headers = {"content-type": "application/json"}
        body = {"email": form.email.data, "password": form.password.data}
        response = requests.post(
            url=url, headers=headers, data=json.dumps(body))

        if response.status_code == 200:
            flash('You are logged in!', 'success')
            token = json.loads(response.text)['access_token']
            resp = make_response(redirect(url_for('main.home')))
            set_access_cookies(resp, encoded_access_token=token)
            
            return resp
        
        if response.status_code == 422:
            log.error(response.text)

        if response.status_code == 401:
            flash('email and password combination not valid', 'danger')

        if response.status_code == 500:
            flash(
                f'Something went wrong with user registration, try again later', 'warning')

    return render_template('login.html.jinja',
                           title=title,
                           form=form)

@blp.route('/logout')
def logout():
    if "access_token_cookie" in request.cookies:  
        resp = make_response(redirect(url_for('main.home')))
        unset_access_cookies(response=resp)
        flash('You have been logged out!', 'success')
        return resp
    flash('you are not logged in', 'warning')
    return redirect(url_for('main.home'))
    


@blp.route('/register', methods=['GET', 'POST'])
def register():

    title = 'Register'
    form = RegistrationFrom()

    if form.validate_on_submit():

        url = f"{AUTH_PROJECTS_FULL_PATH}/register"
        headers = {"content-type": "application/json"}
        body = {"email": form.email.data, "password": form.password.data}
        response = requests.post(
            url=url, headers=headers, data=json.dumps(body))

        if response.status_code == 201:
            flash(f'Your accoun as been created', 'success')
            return redirect(url_for('main.login'))

        if response.status_code == 409:
            flash(f'account with email {form.email} already exists!', 'danger')

        if response.status_code == 500:
            flash(
                f'Something went wrong with user registration, try again later', 'warning')

    return render_template('register.html.jinja',
                           title=title,
                           form=form)

@jwt.unauthorized_loader
def custom_unauthorized_response(_err):
    flash('you are not authorized to visit this page. Please log in', 'danger')
    return redirect(url_for('main.login'))

frontend/templates/partials/nav-main.html.jinja
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <!-- Logo -->
    <span class="navbar-brand mb-0 h1">Music Projects</span>

    <!-- Navbar Toggler (for mobile) -->
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Navbar Links -->
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="#">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('project.projects') }}">Projects</a>
        </li>
      </ul>
      <ul class="navbar-nav">
      {% if not is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('main.register') }}">Register</a>
        </li>      
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('main.login') }}">Login</a>
        </li>
        {% else %}
        </li>      
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('main.logout') }}">Logout</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

frontend/templates/partials/nav-project.html.jinja
<nav class="navbar navbar-expand-lg">
  <div class="container">
    <!-- Navbar Links -->
    <div class="collapse navbar-collapse justify-content-center" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('project.description',project_id=project_id) }}">Description</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('project.tasks',project_id=project_id) }}">Tasks</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('project.repertoire',project_id=project_id) }}">Repertoire</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('project.part_allocation',project_id=project_id) }}">Part Allocation</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('project.cast',project_id=project_id) }}">Cast</a>
        </li>
      </ul>
    </div>
  </div>
</nav>